// Comprehensive Movie Dataset - 300+ Movies
const movies = [
  // ═══ SCI-FI (50 movies) ═══
  { title: "Inception", genre: "Sci-Fi", year: 2010, keywords: ["dreams", "reality", "heist", "mind-bending"] },
  { title: "Interstellar", genre: "Sci-Fi", year: 2014, keywords: ["space", "time-travel", "father-daughter", "wormhole"] },
  { title: "The Matrix", genre: "Sci-Fi", year: 1999, keywords: ["simulation", "technology", "action", "dystopia"] },
  { title: "Avatar", genre: "Sci-Fi", year: 2009, keywords: ["aliens", "nature", "war", "colonialism"] },
  { title: "The Martian", genre: "Sci-Fi", year: 2015, keywords: ["survival", "mars", "science", "astronaut"] },
  { title: "Gravity", genre: "Sci-Fi", year: 2013, keywords: ["space", "survival", "astronaut", "isolation"] },
  { title: "Ex Machina", genre: "Sci-Fi", year: 2014, keywords: ["AI", "robot", "consciousness", "thriller"] },
  { title: "Arrival", genre: "Sci-Fi", year: 2016, keywords: ["aliens", "language", "time", "first-contact"] },
  { title: "Blade Runner 2049", genre: "Sci-Fi", year: 2017, keywords: ["dystopia", "AI", "identity", "noir"] },
  { title: "Blade Runner", genre: "Sci-Fi", year: 1982, keywords: ["dystopia", "AI", "android", "noir"] },
  { title: "2001: A Space Odyssey", genre: "Sci-Fi", year: 1968, keywords: ["space", "AI", "evolution", "mind-bending"] },
  { title: "Dune", genre: "Sci-Fi", year: 2021, keywords: ["desert", "politics", "chosen-one", "epic"] },
  { title: "Dune: Part Two", genre: "Sci-Fi", year: 2024, keywords: ["desert", "war", "prophecy", "epic"] },
  { title: "Minority Report", genre: "Sci-Fi", year: 2002, keywords: ["future", "crime", "surveillance", "police"] },
  { title: "Elysium", genre: "Sci-Fi", year: 2013, keywords: ["dystopia", "class-struggle", "robots", "future"] },
  { title: "District 9", genre: "Sci-Fi", year: 2009, keywords: ["aliens", "apartheid", "transformation", "documentary"] },
  { title: "Edge of Tomorrow", genre: "Sci-Fi", year: 2014, keywords: ["time-loop", "aliens", "war", "action"] },
  { title: "Looper", genre: "Sci-Fi", year: 2012, keywords: ["time-travel", "assassin", "future", "paradox"] },
  { title: "Tenet", genre: "Sci-Fi", year: 2020, keywords: ["time", "inversion", "spy", "mind-bending"] },
  { title: "Annihilation", genre: "Sci-Fi", year: 2018, keywords: ["aliens", "mutation", "mystery", "psychological"] },
  { title: "Moon", genre: "Sci-Fi", year: 2009, keywords: ["isolation", "clone", "space", "identity"] },
  { title: "Prometheus", genre: "Sci-Fi", year: 2012, keywords: ["aliens", "origins", "space", "horror"] },
  { title: "Alien", genre: "Sci-Fi", year: 1979, keywords: ["horror", "space", "survival", "monster"] },
  { title: "Aliens", genre: "Sci-Fi", year: 1986, keywords: ["action", "space", "marines", "aliens"] },
  { title: "The Terminator", genre: "Sci-Fi", year: 1984, keywords: ["AI", "time-travel", "apocalypse", "action"] },
  { title: "Terminator 2: Judgment Day", genre: "Sci-Fi", year: 1991, keywords: ["AI", "time-travel", "action", "family"] },
  { title: "Total Recall", genre: "Sci-Fi", year: 1990, keywords: ["memory", "mars", "identity", "action"] },
  { title: "The Fifth Element", genre: "Sci-Fi", year: 1997, keywords: ["space", "comedy", "action", "colorful"] },
  { title: "Star Wars: A New Hope", genre: "Sci-Fi", year: 1977, keywords: ["space", "rebellion", "epic", "classic"] },
  { title: "Star Wars: The Empire Strikes Back", genre: "Sci-Fi", year: 1980, keywords: ["space", "dark", "epic", "twist"] },
  { title: "Star Wars: Return of the Jedi", genre: "Sci-Fi", year: 1983, keywords: ["space", "redemption", "epic", "finale"] },
  { title: "Star Trek", genre: "Sci-Fi", year: 2009, keywords: ["space", "exploration", "time-travel", "reboot"] },
  { title: "Guardians of the Galaxy", genre: "Sci-Fi", year: 2014, keywords: ["space", "comedy", "team", "music"] },
  { title: "Ready Player One", genre: "Sci-Fi", year: 2018, keywords: ["VR", "gaming", "dystopia", "adventure"] },
  { title: "The Matrix Reloaded", genre: "Sci-Fi", year: 2003, keywords: ["simulation", "action", "philosophy", "sequel"] },
  { title: "The Matrix Revolutions", genre: "Sci-Fi", year: 2003, keywords: ["simulation", "war", "finale", "action"] },
  { title: "I, Robot", genre: "Sci-Fi", year: 2004, keywords: ["AI", "robots", "mystery", "action"] },
  { title: "A.I. Artificial Intelligence", genre: "Sci-Fi", year: 2001, keywords: ["AI", "robot-child", "emotion", "future"] },
  { title: "Children of Men", genre: "Sci-Fi", year: 2006, keywords: ["dystopia", "hope", "survival", "pregnancy"] },
  { title: "Snowpiercer", genre: "Sci-Fi", year: 2013, keywords: ["train", "class-struggle", "dystopia", "survival"] },
  { title: "Oblivion", genre: "Sci-Fi", year: 2013, keywords: ["post-apocalyptic", "memory", "aliens", "mystery"] },
  { title: "Gattaca", genre: "Sci-Fi", year: 1997, keywords: ["genetics", "discrimination", "space", "identity"] },
  { title: "The Prestige", genre: "Sci-Fi", year: 2006, keywords: ["magic", "rivalry", "twists", "obsession"] },
  { title: "Source Code", genre: "Sci-Fi", year: 2011, keywords: ["time-loop", "train", "terrorism", "thriller"] },
  { title: "Predestination", genre: "Sci-Fi", year: 2014, keywords: ["time-travel", "paradox", "identity", "mind-bending"] },
  { title: "Coherence", genre: "Sci-Fi", year: 2013, keywords: ["parallel-universe", "dinner-party", "low-budget", "mind-bending"] },
  { title: "Primer", genre: "Sci-Fi", year: 2004, keywords: ["time-travel", "complex", "low-budget", "engineers"] },
  { title: "Donnie Darko", genre: "Sci-Fi", year: 2001, keywords: ["time-travel", "psychological", "teen", "cult"] },
  { title: "Contact", genre: "Sci-Fi", year: 1997, keywords: ["aliens", "first-contact", "science", "faith"] },
  { title: "War of the Worlds", genre: "Sci-Fi", year: 2005, keywords: ["aliens", "invasion", "survival", "family"] },

  // ═══ ACTION / SUPERHERO (60 movies) ═══
  { title: "The Dark Knight", genre: "Action", year: 2008, keywords: ["superhero", "joker", "justice", "batman"] },
  { title: "The Dark Knight Rises", genre: "Action", year: 2012, keywords: ["superhero", "batman", "finale", "revolution"] },
  { title: "Batman Begins", genre: "Action", year: 2005, keywords: ["superhero", "origin", "batman", "fear"] },
  { title: "Gladiator", genre: "Action", year: 2000, keywords: ["rome", "revenge", "historical", "epic"] },
  { title: "Avengers: Endgame", genre: "Action", year: 2019, keywords: ["superheroes", "team", "marvel", "time-travel"] },
  { title: "Avengers: Infinity War", genre: "Action", year: 2018, keywords: ["superheroes", "team", "marvel", "thanos"] },
  { title: "The Avengers", genre: "Action", year: 2012, keywords: ["superheroes", "team", "marvel", "action"] },
  { title: "Mad Max: Fury Road", genre: "Action", year: 2015, keywords: ["dystopia", "chase", "survival", "post-apocalyptic"] },
  { title: "John Wick", genre: "Action", year: 2014, keywords: ["assassin", "revenge", "hitman", "guns"] },
  { title: "John Wick: Chapter 2", genre: "Action", year: 2017, keywords: ["assassin", "revenge", "hitman", "sequel"] },
  { title: "John Wick: Chapter 3", genre: "Action", year: 2019, keywords: ["assassin", "survival", "hitman", "action"] },
  { title: "Mission: Impossible – Fallout", genre: "Action", year: 2018, keywords: ["spy", "heist", "chase", "twists"] },
  { title: "Mission: Impossible", genre: "Action", year: 1996, keywords: ["spy", "heist", "betrayal", "action"] },
  { title: "Die Hard", genre: "Action", year: 1988, keywords: ["hostage", "cop", "explosive", "christmas"] },
  { title: "Top Gun: Maverick", genre: "Action", year: 2022, keywords: ["military", "pilot", "jets", "legacy"] },
  { title: "Top Gun", genre: "Action", year: 1986, keywords: ["military", "pilot", "jets", "romance"] },
  { title: "Spider-Man: No Way Home", genre: "Action", year: 2021, keywords: ["superhero", "marvel", "multiverse", "spider-man"] },
  { title: "Spider-Man: Into the Spider-Verse", genre: "Animation", year: 2018, keywords: ["superhero", "multiverse", "animation", "spider-man"] },
  { title: "Black Panther", genre: "Action", year: 2018, keywords: ["superhero", "africa", "king", "marvel"] },
  { title: "Iron Man", genre: "Action", year: 2008, keywords: ["superhero", "technology", "billionaire", "marvel"] },
  { title: "Captain America: Civil War", genre: "Action", year: 2016, keywords: ["superheroes", "conflict", "marvel", "war"] },
  { title: "Captain America: The Winter Soldier", genre: "Action", year: 2014, keywords: ["superhero", "spy", "marvel", "conspiracy"] },
  { title: "Thor: Ragnarok", genre: "Action", year: 2017, keywords: ["superhero", "comedy", "marvel", "gods"] },
  { title: "Guardians of the Galaxy Vol. 2", genre: "Action", year: 2017, keywords: ["space", "comedy", "team", "family"] },
  { title: "Doctor Strange", genre: "Action", year: 2016, keywords: ["superhero", "magic", "marvel", "multiverse"] },
  { title: "Shang-Chi", genre: "Action", year: 2021, keywords: ["superhero", "martial-arts", "marvel", "family"] },
  { title: "The Suicide Squad", genre: "Action", year: 2021, keywords: ["antiheroes", "team", "dc", "comedy"] },
  { title: "Wonder Woman", genre: "Action", year: 2017, keywords: ["superhero", "war", "dc", "amazon"] },
  { title: "Man of Steel", genre: "Action", year: 2013, keywords: ["superhero", "superman", "dc", "origin"] },
  { title: "300", genre: "Action", year: 2006, keywords: ["sparta", "war", "historical", "epic"] },
  { title: "Troy", genre: "Action", year: 2004, keywords: ["greece", "war", "historical", "epic"] },
  { title: "Braveheart", genre: "Action", year: 1995, keywords: ["scotland", "war", "historical", "freedom"] },
  { title: "The Bourne Identity", genre: "Action", year: 2002, keywords: ["spy", "amnesia", "chase", "thriller"] },
  { title: "The Bourne Ultimatum", genre: "Action", year: 2007, keywords: ["spy", "chase", "conspiracy", "action"] },
  { title: "Casino Royale", genre: "Action", year: 2006, keywords: ["spy", "bond", "poker", "reboot"] },
  { title: "Skyfall", genre: "Action", year: 2012, keywords: ["spy", "bond", "revenge", "legacy"] },
  { title: "Kingsman: The Secret Service", genre: "Action", year: 2014, keywords: ["spy", "comedy", "training", "british"] },
  { title: "Atomic Blonde", genre: "Action", year: 2017, keywords: ["spy", "cold-war", "action", "female-lead"] },
  { title: "Kill Bill: Vol. 1", genre: "Action", year: 2003, keywords: ["revenge", "martial-arts", "samurai", "stylized"] },
  { title: "Kill Bill: Vol. 2", genre: "Action", year: 2004, keywords: ["revenge", "martial-arts", "finale", "emotional"] },
  { title: "The Raid", genre: "Action", year: 2011, keywords: ["martial-arts", "building", "survival", "indonesian"] },
  { title: "Crouching Tiger, Hidden Dragon", genre: "Action", year: 2000, keywords: ["martial-arts", "romance", "chinese", "wuxia"] },
  { title: "Speed", genre: "Action", year: 1994, keywords: ["bus", "bomb", "chase", "thriller"] },
  { title: "Point Break", genre: "Action", year: 1991, keywords: ["surfing", "robbery", "undercover", "adrenaline"] },
  { title: "Face/Off", genre: "Action", year: 1997, keywords: ["identity", "swap", "revenge", "explosive"] },
  { title: "Con Air", genre: "Action", year: 1997, keywords: ["plane", "prisoners", "rescue", "explosive"] },
  { title: "The Rock", genre: "Action", year: 1996, keywords: ["island", "hostage", "military", "explosive"] },
  { title: "Taken", genre: "Action", year: 2008, keywords: ["kidnapping", "rescue", "skills", "father"] },
  { title: "The Equalizer", genre: "Action", year: 2014, keywords: ["vigilante", "skills", "justice", "revenge"] },
  { title: "Logan", genre: "Action", year: 2017, keywords: ["superhero", "western", "dark", "finale"] },
  { title: "Deadpool", genre: "Action", year: 2016, keywords: ["superhero", "comedy", "fourth-wall", "marvel"] },
  { title: "Deadpool 2", genre: "Action", year: 2018, keywords: ["superhero", "comedy", "time-travel", "sequel"] },
  { title: "Venom", genre: "Action", year: 2018, keywords: ["superhero", "symbiote", "antihero", "marvel"] },
  { title: "The Incredibles", genre: "Animation", year: 2004, keywords: ["superhero", "family", "animation", "pixar"] },
  { title: "The Incredibles 2", genre: "Animation", year: 2018, keywords: ["superhero", "family", "animation", "sequel"] },
  { title: "Big Hero 6", genre: "Animation", year: 2014, keywords: ["superhero", "robot", "animation", "team"] },
  { title: "Kick-Ass", genre: "Action", year: 2010, keywords: ["superhero", "teen", "violence", "comedy"] },
  { title: "Watchmen", genre: "Action", year: 2009, keywords: ["superhero", "dark", "deconstruction", "mystery"] },
  { title: "V for Vendetta", genre: "Action", year: 2005, keywords: ["dystopia", "revolution", "mask", "political"] },

  // ═══ DRAMA (50 movies) ═══
  { title: "Fight Club", genre: "Drama", year: 1999, keywords: ["anarchy", "split-personality", "underground", "twist"] },
  { title: "Parasite", genre: "Drama", year: 2019, keywords: ["class-struggle", "social", "thriller", "korean"] },
  { title: "The Shawshank Redemption", genre: "Drama", year: 1994, keywords: ["prison", "hope", "friendship", "escape"] },
  { title: "Memento", genre: "Drama", year: 2000, keywords: ["memory", "nonlinear", "mystery", "identity"] },
  { title: "Schindler's List", genre: "Drama", year: 1993, keywords: ["war", "holocaust", "heroism", "historical"] },
  { title: "Forrest Gump", genre: "Drama", year: 1994, keywords: ["life", "history", "love", "inspirational"] },
  { title: "The Green Mile", genre: "Drama", year: 1999, keywords: ["prison", "supernatural", "justice", "death-row"] },
  { title: "Good Will Hunting", genre: "Drama", year: 1997, keywords: ["genius", "therapy", "self-discovery", "friendship"] },
  { title: "A Beautiful Mind", genre: "Drama", year: 2001, keywords: ["math", "genius", "mental-illness", "biography"] },
  { title: "Whiplash", genre: "Drama", year: 2014, keywords: ["music", "ambition", "obsession", "pressure"] },
  { title: "La La Land", genre: "Drama", year: 2016, keywords: ["music", "dreams", "romance", "los-angeles"] },
  { title: "The Revenant", genre: "Drama", year: 2015, keywords: ["survival", "revenge", "wilderness", "bear"] },
  { title: "12 Years a Slave", genre: "Drama", year: 2013, keywords: ["slavery", "historical", "freedom", "injustice"] },
  { title: "American History X", genre: "Drama", year: 1998, keywords: ["racism", "redemption", "gangs", "family"] },
  { title: "Requiem for a Dream", genre: "Drama", year: 2000, keywords: ["addiction", "dark", "dreams", "drugs"] },
  { title: "The Social Network", genre: "Drama", year: 2010, keywords: ["tech", "betrayal", "startup", "facebook"] },
  { title: "Bohemian Rhapsody", genre: "Drama", year: 2018, keywords: ["music", "queen", "biography", "freddie-mercury"] },
  { title: "The Imitation Game", genre: "Drama", year: 2014, keywords: ["war", "codebreaking", "genius", "turing"] },
  { title: "Oppenheimer", genre: "Drama", year: 2023, keywords: ["war", "nuclear", "science", "biography"] },
  { title: "There Will Be Blood", genre: "Drama", year: 2007, keywords: ["oil", "greed", "ambition", "period"] },
  { title: "The Pianist", genre: "Drama", year: 2002, keywords: ["war", "holocaust", "survival", "music"] },
  { title: "Life is Beautiful", genre: "Drama", year: 1997, keywords: ["war", "holocaust", "father", "hope"] },
  { title: "The Pursuit of Happyness", genre: "Drama", year: 2006, keywords: ["poverty", "father", "hope", "inspirational"] },
  { title: "Dead Poets Society", genre: "Drama", year: 1989, keywords: ["school", "poetry", "inspiration", "teacher"] },
  { title: "Stand by Me", genre: "Drama", year: 1986, keywords: ["friendship", "coming-of-age", "nostalgia", "adventure"] },
  { title: "The Breakfast Club", genre: "Drama", year: 1985, keywords: ["high-school", "detention", "coming-of-age", "friendship"] },
  { title: "Moonlight", genre: "Drama", year: 2016, keywords: ["identity", "lgbtq", "coming-of-age", "miami"] },
  { title: "Birdman", genre: "Drama", year: 2014, keywords: ["theater", "ego", "one-shot", "comeback"] },
  { title: "Spotlight", genre: "Drama", year: 2015, keywords: ["journalism", "investigation", "church", "true-story"] },
  { title: "The King's Speech", genre: "Drama", year: 2010, keywords: ["royalty", "speech", "friendship", "historical"] },
  { title: "Slumdog Millionaire", genre: "Drama", year: 2008, keywords: ["india", "poverty", "love", "game-show"] },
  { title: "Million Dollar Baby", genre: "Drama", year: 2004, keywords: ["boxing", "mentor", "tragedy", "determination"] },
  { title: "Crash", genre: "Drama", year: 2004, keywords: ["racism", "los-angeles", "ensemble", "social"] },
  { title: "The Departed", genre: "Drama", year: 2006, keywords: ["crime", "undercover", "boston", "mafia"] },
  { title: "Mystic River", genre: "Drama", year: 2003, keywords: ["murder", "friendship", "trauma", "boston"] },
  { title: "Manchester by the Sea", genre: "Drama", year: 2016, keywords: ["grief", "family", "tragedy", "emotional"] },
  { title: "Room", genre: "Drama", year: 2015, keywords: ["captivity", "mother", "escape", "trauma"] },
  { title: "Lion", genre: "Drama", year: 2016, keywords: ["adoption", "india", "search", "true-story"] },
  { title: "Hidden Figures", genre: "Drama", year: 2016, keywords: ["nasa", "racism", "women", "space"] },
  { title: "The Theory of Everything", genre: "Drama", year: 2014, keywords: ["science", "hawking", "love", "disability"] },
  { title: "Dallas Buyers Club", genre: "Drama", year: 2013, keywords: ["aids", "activism", "transformation", "true-story"] },
  { title: "127 Hours", genre: "Drama", year: 2010, keywords: ["survival", "trapped", "amputation", "true-story"] },
  { title: "Into the Wild", genre: "Drama", year: 2007, keywords: ["nature", "freedom", "journey", "true-story"] },
  { title: "Cast Away", genre: "Drama", year: 2000, keywords: ["survival", "island", "isolation", "volleyball"] },
  { title: "The Truman Show", genre: "Drama", year: 1998, keywords: ["reality-tv", "surveillance", "identity", "twist"] },
  { title: "Eternal Sunshine of the Spotless Mind", genre: "Drama", year: 2004, keywords: ["memory", "love", "mind-bending", "breakup"] },
  { title: "Her", genre: "Drama", year: 2013, keywords: ["AI", "love", "loneliness", "future"] },
  { title: "Lost in Translation", genre: "Drama", year: 2003, keywords: ["loneliness", "tokyo", "connection", "melancholy"] },
  { title: "Before Sunrise", genre: "Drama", year: 1995, keywords: ["romance", "conversation", "vienna", "connection"] },
  { title: "Before Sunset", genre: "Drama", year: 2004, keywords: ["romance", "conversation", "paris", "reunion"] },
